SkyLove/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from SkyLove import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('manager.urls', namespace='manager')),
    path('', include('apptevent.urls', namespace='apptevent')),
    path('', include('inventory.urls', namespace='inventory')),
    path('', include('action.urls', namespace='action')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)
urlpatterns += static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

action/urls.py
from django.urls import path
from . import views

app_name = 'action'

urlpatterns = [

  # Treatment Routes
  path('treatment/overview', views.treatment_overview, name='treatment_overview'),
  path('treatment/new/', views.TreatmentNew.as_view(), name='treatment_new'),
  path('treatment/newaddfee/', views.treatment_new, name='treatment_new_add_fee'),
  path('treatment/<int:pk>/view/', views.TreatmentView.as_view(), name='treatment_view'),
  path('treatment/<int:pk>/update/', views.TreatmentUpdate.as_view(), name='treatment_update'),
  path('treatment/<int:pk>/append/', views.TreatmentAppend.as_view(), name='treatment_append'),
  # path('treatment/<int:pk>/delete/', views.TreatmentTag_Delete.as_view(), name='treatment_delete'),

  path('treatmentpro/<int:pk>/update/', views.TreatmentProcessUpdate.as_view(), name='treatment_pro_update'),
  path('treatmentpro/<int:pk>/addimg/', views.upload_images, name='treatment_pro_add_img'),
  path('treatmentpro/<int:pk>/preimg/', views.image_preview, name='treatment_pro_prev_img'),
  path('treatmentpro/<int:pk>/deltmpimgs/', views.delete_tmp_images, name='treatment_pro_del_tmp_img'),
  path('treat_img_delete/<int:pk>/<int:img_tag>',
       views.treatment_process_update_delete,
       name='treatment_pro_update_delete'),

  path('treatment/<int:pk>/asset/', views.TreatmentAssetAdd.as_view(), name='treatment_asset'),
  path('treatment/<int:pk>/assetedit/', views.TreatmentAssetUpdate.as_view(), name='treatment_asset_edit'),

  # Consulting Routes
  path('consultant/overview', views.consulting_overview, name='consultant_overview'),
  path('consultant/new/', views.ConsultingNew.as_view(), name='consultant_new'),
  path('consultant/<int:pk>/view/', views.ConsultingView.as_view(), name='consultant_view'),
  path('consultant/<int:pk>/update/', views.ConsultingUpdate.as_view(), name='consultant_update'),

  # Invoice
  path('invoice/overview', views.invoice_overview, name='invoice_overview'),
  path('invoice/new/', views.InvoiceNew.as_view(), name='invoice_new'),
  path('invoice/<int:pk>/view/', views.InvoiceView.as_view(), name='invoice_view'),
  path('invoice/<int:pk>/viewpdf/', views.InvoiceViewPdf.as_view(), name='invoice_view_pdf'),
  path('invoice/<int:pk>/update/', views.InvoiceUpdate.as_view(), name='invoice_update'),
  path('invoice/<int:pk>/append/', views.InvoiceAppend.as_view(), name='invoice_append'),

  path('invoice/debt', views.invoice_debt, name='invoice_debt'),
  path('invoice/debt/csv', views.debt_view_csv, name='invoice_debt_csv'),

  path('invoicepro/<int:pk>/update/', views.InvoiceProcessUpdate.as_view(), name='invoice_pro_update'),
  path('invoicefee/<int:pk>/init/', views.InvoiceFeeInit.as_view(), name='invoice_fee_init'),
  path('invoicefee/<int:pk>/copy/', views.InvoiceFeeCopy.as_view(), name='invoice_fee_copy'),
  path('invoicefee/<int:pk>/update/', views.InvoiceFeeUpdate.as_view(), name='invoice_fee_update'),
  path('invoicefee/<int:pk>/append/', views.InvoiceAppendFee.as_view(), name='invoice_fee_append'),

  path('invoice/<int:pk>/prt', views.invoice_exp_pdf, name='invoice_prt_demo'),

]

apptevent/urls.py
from django.urls import path
from . import views

app_name = 'apptevent'

urlpatterns = [

    # Appointment Routes
    path('apptevent/', views.CalendarView.as_view(), name='calendar'),
    path('apptevent/new/', views.event, name='event_new'),
    path('apptevent/edit/<int:event_id>/', views.event, name='event_edit'),
    path('apptevent/overview', views.appointment_overview, name='event_overview'),
    path('apptevent/doctor', views.AppointmentDoctor.as_view(), name='event_doctor'),

]

inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [

    # Asset Routes
    path('asset/', views.AssetAll.as_view(), name='asset_all'),
    path('asset/new/', views.AssetNew.as_view(), name='asset_new'),
    path('asset/<int:pk>/update/', views.AssetUpdate.as_view(), name='asset_update'),
    path('asset/<int:pk>/view/', views.AssetView.as_view(), name='asset_view'),

    # Inventory Routes
    path('inventory/', views.inventory_overview, name='inv_all'),
    path('inventory/csv/', views.inventory_view_csv, name='inv_all_csv'),
    path('inventory/new/', views.PurchaseNew.as_view(), name='inv_new'),

    path('invout/overview/', views.deliver_overview, name='out_all'),
    path('invout/csv/', views.delivery_view_csv, name='out_all_csv'),

    # AssetCategory Routes
    path('assetcategory/', views.AssetCategoryAll.as_view(), name='ass_cat_all'),
    path('assetcategory/new/', views.AssetCategoryNew.as_view(), name='ass_cat_new'),
    path('assetcategory/<int:pk>/update/', views.AssetCategoryUpdate.as_view(), name='ass_cat_update'),

    # AssetUnit Routes
    path('assetunit/', views.AssetUnitAll.as_view(), name='ass_unt_all'),
    path('assetunit/new/', views.AssetUnitNew.as_view(), name='ass_unt_new'),
    path('assetunit/<int:pk>/update/', views.AssetUnitUpdate.as_view(), name='ass_unt_update'),

    # Supplier Routes
    path('supplier/', views.SupplierAll.as_view(), name='supplier_all'),
    path('supplier/new/', views.SupplierNew.as_view(), name='supplier_new'),
    path('supplier/<int:pk>/update/', views.SupplierUpdate.as_view(), name='supplier_update'),
    path('supplier/<int:pk>/view/', views.SupplierView.as_view(), name='supplier_view'),

]

manager/urls.py
from django.urls import path
from . import views

app_name = 'manager'

urlpatterns = [
    # Authentication Routes
    path('', views.Index.as_view(), name='index'),
    path('register/', views.Register.as_view(), name='reg'),
    path('login/', views.LoginViewer.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('user/<int:pk>/update', views.UserUpdate.as_view(), name='user_update'),
    path('user/password_change', views.password_change, name='user_password_change'),

    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path('birthday/', views.BirthdayView.as_view(), name='birthday'),

    # Employee Routes
    path('employee/', views.EmployeeAll.as_view(), name='employee_all'),
    path('employee/new/', views.EmployeeNew.as_view(), name='employee_new'),
    path('employee/<int:pk>/view/', views.EmployeeView.as_view(), name='employee_view'),
    path('employee/<int:pk>/update/', views.EmployeeUpdate.as_view(), name='employee_update'),
    path('employee/<int:pk>/delete/', views.EmployeeDelete.as_view(), name='employee_delete'),

    # Department Routes
    path('department/all/', views.DepartmentAll.as_view(), name='dept_all'),
    path('department/add/', views.DepartmentNew.as_view(), name='dept_new'),
    path('department/<int:pk>/update/', views.DepartmentUpdate.as_view(), name='dept_update'),

    # path('customer/dashboard', views.Dashboard.as_view(), name='dashboard'),
    path('customer/overview', views.customer_overview, name='customer_overview'),
    path('customer/all', views.CustomerAll.as_view(), name='customer_all'),
    path('customer/new/', views.CustomerNew.as_view(), name='customer_new'),
    path('customer/<int:pk>/view/', views.CustomerView.as_view(), name='customer_view'),
    path('customer/<int:pk>/update/', views.CustomerUpdate.as_view(), name='customer_update'),
    path('customer/<int:pk>/delete/', views.CustomerDelete.as_view(), name='customer_delete'),

    # Customer Source Routes
    path('customer/source/', views.CustomerSourceAll.as_view(), name='cust_src_all'),
    path('customer/source/add/', views.CustomerSourceNew.as_view(), name='cust_src_new'),
    path('customer/source/<int:pk>/update/', views.CustomerSourceUpdate.as_view(), name='cust_src_update'),

    # Service Routes
    path('service/', views.ServiceAll.as_view(), name='app_srv_all'),
    path('service/add/', views.ServiceNew.as_view(), name='app_srv_new'),
    path('service/<int:pk>/update/', views.ServiceUpdate.as_view(), name='app_srv_update'),

]

manager/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, SetPasswordForm

from manager.models import Employee, Department, CustomerSource, Customer, Service


class RegistrationForm(UserCreationForm):
    fullname = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Fullname'}))
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Valid Email is required'}))
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}))
    thumb = forms.ImageField(
        label='Image:', required=False,
        widget=forms.FileInput(attrs={'class': 'form-control mt-2'})
    )

    class Meta:
        model = get_user_model()
        fields = ('fullname', 'username', 'email', 'password1', 'password2', 'thumb')


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'autofocus': True, 'placeholder': 'Username', 'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '********'}))


class UserUpdateForm(forms.ModelForm):
    fullname = forms.CharField(
        label='Họ tên:',
        max_length=32,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'FullName'})
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Valid Email is required'}))
    thumb = forms.ImageField(
        label='Hình ảnh:', required=False,
        widget=forms.ClearableFileInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = get_user_model()
        fields = ('fullname', 'email', 'thumb')


class SetPasswordForm(SetPasswordForm):
    class Meta:
        model = get_user_model()
        fields = ['new_password1', 'new_password2']


class DepartmentForm(forms.ModelForm):
    name = forms.CharField(
        label='Tên bộ phận:',
        max_length=20,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Department Name'}))

    class Meta:
        model = Department
        fields = '__all__'


class EmployeeForm(forms.ModelForm):
    humanID = \
        forms.CharField(
            label='Số CCCD/Hộ chiếu:[*]',
            strip=True,
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Citizen-ID'})
        )
    fullname = \
        forms.CharField(
            label='Họ tên:[*]',
            strip=True,
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Full Name'})
        )
    dob = \
        forms.DateField(
            label='Ngày sinh:[*]',
            widget=forms.DateInput(attrs={'type': 'date'})
        )
    mobile = \
        forms.CharField(
            label='Số điện thoại:[*]',
            strip=True,
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Mobile Number'})
        )
    email = \
        forms.CharField(
            strip=True, required=False,
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'abc@xyz.com'})
        )
    gender = \
        forms.ChoiceField(
            label='Giới tính:[*]',
            choices=Employee.GENDER, widget=forms.Select(attrs={'class': 'form-control'})
        )
    address = \
        forms.CharField(
            label='Địa chỉ:',
            strip=True, required=False,
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address'})
        )
    department = \
        forms.ModelChoiceField(
            Department.objects.all(),
            required=True,
            label='Bộ phận:[*]',
            empty_label='Chọn bộ phận',
            widget=forms.Select(attrs={'class': 'form-control'})
        )
    language = \
        forms.ChoiceField(
            label='Ngôn ngữ',
            required=False,
            choices=Employee.LANGUAGE,
            widget=forms.Select(attrs={'class': 'form-control'})
        )
    thumb = \
        forms.ImageField(
            required=False,
            label='Hình ảnh:',
            widget=forms.ClearableFileInput(attrs={'class': 'form-control'})
        )

    class Meta:
        model = Employee
        fields = (
            'fullname', 'humanID', 'dob', 'mobile', 'email', 'address', 'salary', 'gender', 'department',
            'bank', 'nubank', 'language', 'thumb')
        widgets = {
            'salary': forms.TextInput(attrs={'class': 'form-control'}),
            'bank': forms.TextInput(attrs={'class': 'form-control'}),
            'nubank': forms.TextInput(attrs={'class': 'form-control'})
        }


class CustomerForm(forms.ModelForm):
    fullname = \
        forms.CharField(
            label='Họ tên:[*]',
            strip=True,
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Full Name'})
        )
    mobile = \
        forms.CharField(
            label='Số điện thoại:[*]',
            strip=True,
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Mobile Number'})
        )
    yob = \
        forms.IntegerField(
            label='Năm sinh:[*]',
            widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Year of Birth'})
        )
    dob = \
        forms.DateField(
            label='Ngày sinh:',
            required=False,
            widget=forms.DateInput(attrs={'type': 'date'})
        )
    humanID = \
        forms.CharField(
            label='Số CCCD/Hộ chiếu:',
            strip=True, required=False,
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Citizen-ID'})
        )
    email = \
        forms.CharField(
            strip=True, required=False,
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'abc@xyz.com'})
        )
    gender = \
        forms.ChoiceField(
            label='Giới tính:[*]',
            choices=Customer.GENDER, widget=forms.Select(attrs={'class': 'form-control'})
        )
    address = \
        forms.CharField(
            label='Địa chỉ:',
            strip=True, required=False,
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address'})
        )
    source = \
        forms.ModelChoiceField(
            CustomerSource.objects.all(),
            label='Nguồn Khách Hàng:',
            required=False,
            empty_label='Chọn nguồn KH',
            widget=forms.Select(attrs={'class': 'form-control'})
        )
    nubank = \
        forms.CharField(
            label='Số tài khoản NH:',
            strip=True, required=False,
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Bank account'})
        )
    thumb = \
        forms.ImageField(
            required=False,
            label='Hình ảnh:',
            widget=forms.ClearableFileInput(attrs={'class': 'form-control'})
        )

    class Meta:
        model = Customer
        fields = (
            'fullname', 'mobile', 'yob', 'dob', 'humanID', 'email', 'gender', 'address', 'source', 'nubank', 'thumb'
        )


class CustomerSourceForm(forms.ModelForm):
    name = forms.CharField(
        max_length=64,
        label='Nguồn KH',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Chọn nguồn KH'})
    )

    class Meta:
        model = CustomerSource
        fields = '__all__'


class CustomerFilterForm(forms.Form):
    mobile: forms.CharField()


class ServiceForm(forms.ModelForm):
    name = forms.CharField(
        max_length=64,
        label='Loại DV',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Loại DV'})
    )

    class Meta:
        model = Service
        fields = ('id', 'name', 'cost')
        labels = {'cost': 'Giá tiền:'}

manager/templates/manager/footer.html
<footer class="footer bg-dark text-white">
  <div class="container-fluid clearfix">
    <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">
      Copyright © 2022
      <a href="https://www.facebook.com/seasun.enter/" target="_blank">SLyLove Clinic Management System. </a>
      All rights reserved.
    </span>
    <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">
      Developed by ®SeaSunSoft
    </span>
  </div>
</footer>

manager/templates/manager/sidebar.html
{% load static %}
<nav class="sidebar sidebar-offcanvas bg-inverse-info" id="sidebar">
  <ul class="nav">
    <li class="nav-item nav-profile">
      <div class="nav-link">
        <div class="user-wrapper">
          <div class="profile-image">
            {% if user.thumb.url != null %}
              <img src="{{ user.thumb.url }}" class='rounded img-fluid' alt="">
            {% else %}
              <img src="{% static 'images/No_Image.png' %}" class='rounded img-fluid' alt="">
            {% endif %}

          </div>
          <div class="text-wrapper">
            <p class="profile-name">{{ user.username | upper }} </p>
            <div>
              <small class="designation text-dark">
                {% if user.is_superuser > 0 %}
                  Administrator
                {% else %}
                  Admin
                {% endif %}
              </small>
              <span class="status-indicator online"></span>
            </div>
          </div>
        </div>
        <!---
        <a href="% url 'action:treatment_overview' %}" class="btn btn-primary btn-block">
        --->
        <a href="{% url 'manager:customer_overview' %}" class="btn btn-primary btn-block">
          <i class="mdi mdi-phone"></i>
          &emsp;Mobile / Name
        </a>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'manager:dashboard' %}">
        <i class="fa fa-desktop"></i>
        <span class="menu-title">&emsp;&emsp;&emsp;Dashboard</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'manager:customer_all' %}">
        <i class="fa fa-users text-dark"></i>
        <span class="menu-title">&emsp;&emsp;&emsp;Khách Hàng</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'apptevent:calendar' %}">
        <i class="fa fa-calendar"></i>
        <span class="menu-title">&emsp;&emsp;&emsp;Lịch Hẹn</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'action:consultant_overview' %}">
        <i class="fa fa-address-book-o"></i>
        <span class="menu-title">&emsp;&emsp;&emsp;Tư Vấn</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'action:treatment_overview' %}">
        <i class="fa fa-newspaper-o"></i>
        <span class="menu-title">&emsp;&emsp;&emsp;Liệu Trình</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#ui-accountant" aria-expanded="false" aria-controls="ui-accountant">
        <i class="fa fa-money"></i>
        <span class="menu-title">&emsp;&emsp;&emsp;Tài chính</span>
        <i class="menu-arrow"></i>
      </a>
      <hr>
      <div class="collapse" id="ui-accountant">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'action:invoice_overview' %}">
              <i class="fa fa-usd"></i>
              <span class="menu-title">&emsp;&emsp;&emsp;Thanh Toán</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'action:invoice_debt' %}">
              <i class="mdi mdi-book-open-variant"></i>&emsp;&emsp;&emsp;Công Nợ
            </a>
          </li>
        </ul>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#ui-asset" aria-expanded="false" aria-controls="ui-asset">
        <i class="fa fa-archive"></i>
        <span class="menu-title">&emsp;&emsp;&emsp;Vật Tư</span>
        <i class="menu-arrow"></i>
      </a>
      <hr>
      <div class="collapse" id="ui-asset">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'inventory:asset_all' %}">
              <i class="mdi mdi-store"></i>&emsp;&emsp;&emsp;Y Dụng Cụ
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'inventory:asset_new' %}">
              <i class="mdi mdi-import"></i>&emsp;&emsp;&emsp;Nhập Thêm
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'inventory:ass_cat_all' %}">
              <i class="mdi mdi-tag"></i>&emsp;&emsp;&emsp;Danh Mục
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'inventory:ass_unt_all' %}">
              <i class="mdi mdi-code-tags"></i>&emsp;&emsp;&emsp;Đơn Vị Tính
            </a>
          </li>
        </ul>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'inventory:supplier_all' %}">
        <i class="fa fa-user-md"></i>
        <span class="menu-title">&emsp;&emsp;&emsp;Nhà Cung Cấp</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#ui-inventory" aria-expanded="false"
         aria-controls="ui-inventory">
        <i class="fa fa-industry"></i>
        <span class="menu-title">&emsp;&emsp;&emsp;Kho Hàng</span>
        <i class="menu-arrow"></i>
      </a>
      <hr>
      <div class="collapse" id="ui-inventory">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'inventory:inv_all' %}">
              <i class="mdi mdi-store"></i>&emsp;&emsp;&emsp;Kiểm Kho
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'inventory:inv_new' %}">
              <i class="mdi mdi-import"></i>&emsp;&emsp;&emsp;Nhập Hàng
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'inventory:out_all' %}">
              <i class="mdi mdi-export"></i>&emsp;&emsp;&emsp;Hàng Xuất
            </a>
          </li>
        </ul>
      </div>
    </li>

    <!---
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
        <i class="fa fa-folder "></i>
        <span class="menu-title">&emsp;Department</span>
        <i class="menu-arrow"></i>
      </a>
      <a class="nav-link" href=""><i class="fa fa-plus"></i>&emsp;New Department</a>
      <hr>
      <div class="collapse" id="ui-basic">
        <ul class="nav flex-column sub-menu">
          % for dept in departments %}
            <li class="nav-item">
              <a class="nav-link" href="">{ dept.name }}</a>
            </li>
          % endfor %}
        </ul>
      </div>
    </li>
    --->
    <li class="nav-item">
      <a class="nav-link" href="{% url 'manager:employee_all' %}" aria-expanded="false" aria-controls="ui-basic">
        <i class="fa fa-user text-dark"></i>
        <span class="menu-title">&emsp;&emsp;&emsp;Nhân Sự</span>
      </a>
    </li>
    <!---
    <li class="nav-item">
      <a class="nav-link" style="pointer-events:none;opacity:0.4;">
        <i class="fa fa-database"></i>
        <span class="menu-title">&emsp;&emsp;&emsp;Chấm Công</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" style="pointer-events:none;opacity:0.4;">
        <i class="fa fa-usd"></i>
        <span class="menu-title">&emsp;&emsp;&emsp;Tính Lương</span>
      </a>
    </li>
    --->
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#ui-config" aria-expanded="false" aria-controls="ui-config">
        <i class="fa fa-gears "></i>
        <span class="menu-title">&emsp;&emsp;&emsp;Cấu hình</span>
        <i class="menu-arrow"></i>
      </a>
      <hr>
      <div class="collapse" id="ui-config">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'manager:dept_all' %}">
              <i class="fa fa-tags"></i>&emsp;&emsp;&emsp;Danh mục
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="fa fa-gear"></i>&emsp;&emsp;&emsp;Thiết lập chung
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="fa fa-info-circle"></i>&emsp;&emsp;&emsp;Hệ thống
            </a>
          </li>
        </ul>
      </div>
    </li>

    {% comment %} <li class="nav-item">

          <li class="nav-item">
            <a class="nav-link" href="pages/icons/font-awesome.html">
              <i class="fa  fa-gears"></i>
              <span class="menu-title">&emsp;Settings</span>
            </a>
          </li> {% endcomment %}
  </ul>
</nav>