SkyLove/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from SkyLove import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('manager.urls', namespace='manager')),
    path('', include('apptevent.urls', namespace='apptevent')),
    path('', include('inventory.urls', namespace='inventory')),
    path('', include('action.urls', namespace='action')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)
urlpatterns += static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

action/urls.py
from django.urls import path
from . import views

app_name = 'action'

urlpatterns = [

  # Treatment Routes
  path('treatment/overview', views.treatment_overview, name='treatment_overview'),
  path('treatment/new/', views.TreatmentNew.as_view(), name='treatment_new'),
  path('treatment/newaddfee/', views.treatment_new, name='treatment_new_add_fee'),
  path('treatment/<int:pk>/view/', views.TreatmentView.as_view(), name='treatment_view'),
  path('treatment/<int:pk>/update/', views.TreatmentUpdate.as_view(), name='treatment_update'),
  path('treatment/<int:pk>/append/', views.TreatmentAppend.as_view(), name='treatment_append'),
  # path('treatment/<int:pk>/delete/', views.TreatmentTag_Delete.as_view(), name='treatment_delete'),

  path('treatmentpro/<int:pk>/update/', views.TreatmentProcessUpdate.as_view(), name='treatment_pro_update'),
  path('treatmentpro/<int:pk>/addimg/', views.upload_images, name='treatment_pro_add_img'),
  path('treatmentpro/<int:pk>/preimg/', views.image_preview, name='treatment_pro_prev_img'),
  path('treatmentpro/<int:pk>/deltmpimgs/', views.delete_tmp_images, name='treatment_pro_del_tmp_img'),
  path('treat_img_delete/<int:pk>/<int:img_tag>',
       views.treatment_process_update_delete,
       name='treatment_pro_update_delete'),

  path('treatment/<int:pk>/asset/', views.TreatmentAssetAdd.as_view(), name='treatment_asset'),
  path('treatment/<int:pk>/assetedit/', views.TreatmentAssetUpdate.as_view(), name='treatment_asset_edit'),

  # Consulting Routes
  path('consultant/overview', views.consulting_overview, name='consultant_overview'),
  path('consultant/new/', views.ConsultingNew.as_view(), name='consultant_new'),
  path('consultant/<int:pk>/view/', views.ConsultingView.as_view(), name='consultant_view'),
  path('consultant/<int:pk>/update/', views.ConsultingUpdate.as_view(), name='consultant_update'),

  # Invoice
  path('invoice/overview', views.invoice_overview, name='invoice_overview'),
  path('invoice/new/', views.InvoiceNew.as_view(), name='invoice_new'),
  path('invoice/<int:pk>/view/', views.InvoiceView.as_view(), name='invoice_view'),
  path('invoice/<int:pk>/viewpdf/', views.InvoiceViewPdf.as_view(), name='invoice_view_pdf'),
  path('invoice/<int:pk>/update/', views.InvoiceUpdate.as_view(), name='invoice_update'),
  path('invoice/<int:pk>/append/', views.InvoiceAppend.as_view(), name='invoice_append'),

  path('invoice/debt', views.invoice_debt, name='invoice_debt'),
  path('invoice/debt/csv', views.debt_view_csv, name='invoice_debt_csv'),

  path('invoicepro/<int:pk>/update/', views.InvoiceProcessUpdate.as_view(), name='invoice_pro_update'),
  path('invoicefee/<int:pk>/init/', views.InvoiceFeeInit.as_view(), name='invoice_fee_init'),
  path('invoicefee/<int:pk>/copy/', views.InvoiceFeeCopy.as_view(), name='invoice_fee_copy'),
  path('invoicefee/<int:pk>/update/', views.InvoiceFeeUpdate.as_view(), name='invoice_fee_update'),
  path('invoicefee/<int:pk>/append/', views.InvoiceAppendFee.as_view(), name='invoice_fee_append'),

  path('invoice/<int:pk>/prt', views.invoice_exp_pdf, name='invoice_prt_demo'),

]

inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [

    # Asset Routes
    path('asset/', views.AssetAll.as_view(), name='asset_all'),
    path('asset/new/', views.AssetNew.as_view(), name='asset_new'),
    path('asset/<int:pk>/update/', views.AssetUpdate.as_view(), name='asset_update'),
    path('asset/<int:pk>/view/', views.AssetView.as_view(), name='asset_view'),

    # Inventory Routes
    path('inventory/', views.inventory_overview, name='inv_all'),
    path('inventory/csv/', views.inventory_view_csv, name='inv_all_csv'),
    path('inventory/new/', views.PurchaseNew.as_view(), name='inv_new'),

    path('invout/overview/', views.deliver_overview, name='out_all'),
    path('invout/csv/', views.delivery_view_csv, name='out_all_csv'),

    # AssetCategory Routes
    path('assetcategory/', views.AssetCategoryAll.as_view(), name='ass_cat_all'),
    path('assetcategory/new/', views.AssetCategoryNew.as_view(), name='ass_cat_new'),
    path('assetcategory/<int:pk>/update/', views.AssetCategoryUpdate.as_view(), name='ass_cat_update'),

    # AssetUnit Routes
    path('assetunit/', views.AssetUnitAll.as_view(), name='ass_unt_all'),
    path('assetunit/new/', views.AssetUnitNew.as_view(), name='ass_unt_new'),
    path('assetunit/<int:pk>/update/', views.AssetUnitUpdate.as_view(), name='ass_unt_update'),

    # Supplier Routes
    path('supplier/', views.SupplierAll.as_view(), name='supplier_all'),
    path('supplier/new/', views.SupplierNew.as_view(), name='supplier_new'),
    path('supplier/<int:pk>/update/', views.SupplierUpdate.as_view(), name='supplier_update'),
    path('supplier/<int:pk>/view/', views.SupplierView.as_view(), name='supplier_view'),

]

manager/urls.py
from django.urls import path
from . import views

app_name = 'manager'

urlpatterns = [
    # Authentication Routes
    path('', views.Index.as_view(), name='index'),
    path('register/', views.Register.as_view(), name='reg'),
    path('login/', views.LoginViewer.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('user/<int:pk>/update', views.UserUpdate.as_view(), name='user_update'),
    path('user/password_change', views.password_change, name='user_password_change'),

    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path('birthday/', views.BirthdayView.as_view(), name='birthday'),

    # Employee Routes
    path('employee/', views.EmployeeAll.as_view(), name='employee_all'),
    path('employee/new/', views.EmployeeNew.as_view(), name='employee_new'),
    path('employee/<int:pk>/view/', views.EmployeeView.as_view(), name='employee_view'),
    path('employee/<int:pk>/update/', views.EmployeeUpdate.as_view(), name='employee_update'),
    path('employee/<int:pk>/delete/', views.EmployeeDelete.as_view(), name='employee_delete'),

    # Department Routes
    path('department/all/', views.DepartmentAll.as_view(), name='dept_all'),
    path('department/add/', views.DepartmentNew.as_view(), name='dept_new'),
    path('department/<int:pk>/update/', views.DepartmentUpdate.as_view(), name='dept_update'),

    # path('customer/dashboard', views.Dashboard.as_view(), name='dashboard'),
    path('customer/overview', views.customer_overview, name='customer_overview'),
    path('customer/all', views.CustomerAll.as_view(), name='customer_all'),
    path('customer/new/', views.CustomerNew.as_view(), name='customer_new'),
    path('customer/<int:pk>/view/', views.CustomerView.as_view(), name='customer_view'),
    path('customer/<int:pk>/update/', views.CustomerUpdate.as_view(), name='customer_update'),
    path('customer/<int:pk>/delete/', views.CustomerDelete.as_view(), name='customer_delete'),

    # Customer Source Routes
    path('customer/source/', views.CustomerSourceAll.as_view(), name='cust_src_all'),
    path('customer/source/add/', views.CustomerSourceNew.as_view(), name='cust_src_new'),
    path('customer/source/<int:pk>/update/', views.CustomerSourceUpdate.as_view(), name='cust_src_update'),

    # Service Routes
    path('service/', views.ServiceAll.as_view(), name='app_srv_all'),
    path('service/add/', views.ServiceNew.as_view(), name='app_srv_new'),
    path('service/<int:pk>/update/', views.ServiceUpdate.as_view(), name='app_srv_update'),

]

inventory/models.py
from django.db import models
from djmoney.models.fields import MoneyField

from manager.models import Customer


# Create your models here.

class Supplier(models.Model):
    name = models.CharField(max_length=32)
    mobile = models.CharField(max_length=16)
    email = models.EmailField(max_length=125, null=False)
    address = models.TextField(max_length=100, default='')
    taxcode = models.CharField(max_length=32)
    nubank = models.CharField(max_length=16, default='0123456789ABCDEF')
    thumb = models.ImageField(blank=True, null=True, upload_to='Supplier')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'Supplier'


class AssetUnit(models.Model):
    name = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'AssetUnit'


class AssetCategory(models.Model):
    name = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'AssetCategory'


class Asset(models.Model):
    name = models.CharField(max_length=80)
    category = models.ForeignKey(AssetCategory, on_delete=models.CASCADE, null=True)
    unitIN = models.ForeignKey(AssetUnit, related_name='UnitIN', on_delete=models.CASCADE, null=False)
    purchase = MoneyField(max_digits=16, decimal_places=0, default_currency='VND', default=0)
    unitINOUT = models.IntegerField(default=1)
    unitOUT = models.ForeignKey(AssetUnit, related_name='UnitOUT', on_delete=models.CASCADE, null=False)
    price = MoneyField(max_digits=16, decimal_places=0, default_currency='VND', default=0)
    thumb = models.ImageField(blank=True, null=True, upload_to='Inventory')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'Asset'


class Inventory(models.Model):
    idIO = models.IntegerField()
    asset = models.ForeignKey(Asset, on_delete=models.CASCADE)
    quantityIO = models.SmallIntegerField()

    class Meta:
        db_table = 'Inventory'


class Purchase(models.Model):
    timeI = models.DateTimeField(auto_now_add=True)
    userID = models.SmallIntegerField()
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = 'Purchase'


class DeliveryTmp(models.Model):
    customer_id = models.SmallIntegerField(null=True)
    customer_name = models.CharField(max_length=40, null=True)
    treatment_id = models.SmallIntegerField(null=True)
    treatment_name = models.CharField(max_length=64, null=True)
    asset_id = models.SmallIntegerField(null=True)
    asset_name = models.CharField(max_length=80, null=True)
    asset_price = MoneyField(max_digits=16, decimal_places=0, default_currency='VND', default=0, null=True)
    quantity = models.SmallIntegerField(null=True)
    paid = MoneyField(max_digits=16, decimal_places=0, default_currency='VND', default=0, null=True)

    class Meta:
        db_table = 'DeliveryTmp'


class InventoryTmp(models.Model):
    timeI = models.DateTimeField(null=True)
    input = models.SmallIntegerField(null=True)
    asset_id = models.SmallIntegerField(null=True)
    asset_name = models.CharField(max_length=80, null=True)
    category_id = models.SmallIntegerField(null=True)
    category_name = models.CharField(max_length=32, null=True)
    timeO = models.DateTimeField(null=True)
    output = models.SmallIntegerField(null=True)
    treatment = models.SmallIntegerField(null=True)
    stock = models.SmallIntegerField(null=True)

    class Meta:
        db_table = 'InventoryTmp'

inventory/forms.py
from django import forms
from inventory.models import AssetCategory, Asset, Supplier, AssetUnit, Purchase, Inventory
from manager.models import Customer


class AssetCategoryForm(forms.ModelForm):
    name = forms.CharField(
        max_length=32,
        label='Loại Vật tư Y-tế:',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Loại Vật-tư'})
    )

    class Meta:
        model = AssetCategory
        fields = '__all__'


class AssetUnitForm(forms.ModelForm):
    name = forms.CharField(
        max_length=32,
        label='Đơn vị tính (Y dụng cụ):',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ĐVT Vật-tư'})
    )

    class Meta:
        model = AssetUnit
        fields = '__all__'


class AssetForm(forms.ModelForm):
    name = forms.CharField(
        max_length=80,
        label='Y dụng cụ [*]:',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Y dụng cụ'})
    )
    category = forms.ModelChoiceField(
        AssetCategory.objects.all(),
        label='Phân loại:',
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    unitIN = forms.ModelChoiceField(
        AssetUnit.objects.all(),
        label='Đơn vị tính (Nhập hàng)[*]:',
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    unitOUT = forms.ModelChoiceField(
        AssetUnit.objects.all(),
        label='Đơn vị tính (Xuất bán)[*]:',
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    unitINOUT = forms.IntegerField(
        label='Số lượng (Xuất bán) trong 1 đơn vị tính (Nhập hàng)[*]:',
        widget=forms.NumberInput()
    )
    thumb = forms.ImageField(
        required=False,
        label='Hình ảnh:',
        widget=forms.ClearableFileInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Asset
        fields = ('name', 'category', 'unitIN', 'unitOUT', 'unitINOUT', 'purchase', 'price', 'thumb')
        labels = {
            'purchase': 'Giá nhập:',
            'price': 'Giá bán:'
        }


class AssetFilterForm(forms.Form):
    category: forms.CharField()


class SupplierForm(forms.ModelForm):
    name = \
        forms.CharField(
            label='Nhà cung cấp:[*]',
            strip=True,
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Supplier Name'})
        )
    mobile = \
        forms.CharField(
            label='Số điện thoại:[*]',
            strip=True,
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Mobile Number'})
        )
    email = \
        forms.CharField(
            strip=True, required=False,
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'abc@xyz.com'})
        )
    address = \
        forms.CharField(
            label='Địa chỉ:',
            strip=True, required=False,
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address'})
        )
    taxcode = \
        forms.CharField(
            label='Mã số thuế:[*]',
            strip=True,
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'MST'})
        )
    nubank = \
        forms.CharField(
            label='Số tài khoản NH:',
            strip=True, required=False,
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Bank account'})
        )
    thumb = \
        forms.ImageField(
            required=False,
            label='Hình ảnh:',
            widget=forms.ClearableFileInput(attrs={'class': 'form-control'})
        )

    class Meta:
        model = Supplier
        fields = '__all__'


class InventoryForm(forms.ModelForm):
    supplier = forms.ModelChoiceField(
        Supplier.objects.all(),
        label='Nhà cung cấp:',
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    asset = forms.ModelChoiceField(
        Asset.objects.all(),
        label='Y dụng cụ:',
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    quantityIO = forms.IntegerField(
        label='Số lượng:',
        widget=forms.NumberInput()
    )

    class Meta:
        model = Purchase
        fields = ('supplier',)


"""
class DeliverForm(forms.ModelForm):
    customer = forms.ModelChoiceField(
        Customer.objects.all(),
        label='Khách hàng:',
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    asset = forms.ModelChoiceField(
        # Asset.objects.all(),
        Asset.objects.filter(inventory__quantityIO__gt=0).order_by('name').distinct(),
        label='Y dụng cụ:',
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    quantityIO = forms.IntegerField(
        label='Số lượng:',
        widget=forms.NumberInput()
    )

    class Meta:
        model = Deliver
        fields = ('customer',)


class DeliverFilterForm(forms.Form):
    category: forms.CharField()
"""

inventory/templates/inventory/out/create.html
{% extends 'manager/layout.html' %}
{% load static %}
{% block title %} Inventory OUT | SkyLove CMS {% endblock title %}

{% block content %}

  <div class="main-panel">
  <div class="content-wrapper">
    <div class="row">
      <!---- <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 grid-margin stretch-card"> --->
      <div class="col-xl-6 col-lg-6 col-md-6 col-sm-4 grid-margin stretch-card">
        <div class="col-lg-12 grid-margin">
          <div class="card">
            <div class="card-body">
              <h4 class="text-center text-primary"><i class="fa fa-plus">&emsp;Xuất hàng </i></h4>
              <hr>
              <!---
              % load bootstrap4 %}
              % bootstrap_css %}
              % bootstrap_javascript jquery='full' %}
              { form.media }} {# Adds widget's JS/CSS files from CDN #}
              --->
              <form enctype="multipart/form-data" action="{% url 'inventory:out_new' %}" class="form-group"
                    method="POST">
                {% csrf_token %}
                <!---
                  % bootstrap_form form %} {# Renders form fields using django-bootstrapX #}
                  <small class="mb-5">Các mục có dấu [*] là bắt buộc</small>
                  --->
                <div class="row"></div>
                {{ form.as_p }}
                <div class="text-center mt-3">
                  <button class="btn btn-outline-success">
                    <i class="mdi mdi-check"></i>
                    Xác Nhận
                  </button>
                  <a href="javascript:history.back();"
                     class="btn btn-outline-danger">
                    <i class="mdi mdi-cancel"></i>Hủy bỏ
                  </a>
                </div>
              </form>

            </div>
          </div>
        </div>
      </div>
      <div class="card-columns">
        <div class="card-body">
          <img src="{{ asset.thumb.url }}" alt="" class="img-fluid" width='150px' height='150px'>
          <p class="lead mt-2 text-center">
            {{ asset.pk | capfirst }}
            <br>
            <small class='text-center text-secondary'>( Photo-ID )</small>
          </p>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}
</div>

inventory/templates/inventory/out/overview.html
{% extends 'manager/layout.html' %}
{% load static %}
{% block title %} All Delivery's Customers | SkyLove CMS {% endblock title %}
<!--  MAIN BODY START HERE -->
{% block content %}
  <div class="main-panel">
  <div class="content-wrapper">
    <div class="row">
      <div class="row">
        <div class="col-lg-12 grid-margin">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title text-primary">
                <div class="lead text-center">
                  HÀNG XUẤT KHO
                </div>
                <br>
              </h4>
              <!---  Table contain customer list --->
              <div class="table-responsive">
                <table class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>
                      Khách hàng
                    </th>
                    <th>
                      Dịch vụ
                    </th>
                    <th>
                      Vật tư
                    </th>
                    <th>
                      Số lượng
                    </th>
                    <th>
                      Giá
                    </th>
                    <th>
                      Thành tiền
                    </th>
                  </tr>
                  </thead>
                  <tbody>
                  {% for delivery in deliveries %}
                    <tr>
                      <td class="font-weight-medium">
                        <a>
                          {% if delivery.customer_name is not None %}
                            <a href="{% url 'manager:customer_view' delivery.customer_id %}">
                              {{ delivery.customer_name }}
                            </a>
                          {% endif %}
                        </a>
                      </td>
                      <td>
                        {% if delivery.treatment_name is not None %}
                          <a href="{% url 'action:treatment_view' delivery.treatment_id %}">
                            {{ delivery.treatment_name }}
                          </a>
                        {% endif %}
                      </td>
                      <td>
                        {% if delivery.asset_name == "Tổng cộng" %}
                          <div class="text-lg-right">
                            {{ delivery.asset_name }}
                          </div>
                        {% else %}
                          <a href="{% url 'inventory:asset_view' delivery.asset_id %}">
                            {{ delivery.asset_name }}
                          </a>
                        {% endif %}
                      </td>
                      <td>
                        {% if delivery.quantity is not None %}
                          <a href="{% url 'action:treatment_view' delivery.treatment_id %}">
                          {{ delivery.quantity }}
                        {% endif %}
                        </a>
                      </td>
                      <td>
                        {% if delivery.asset_price is not None %}
                          <a href="{% url 'inventory:asset_update' delivery.asset_id %}">
                            {{ delivery.asset_price }}
                          </a>
                        {% endif %}
                      </td>
                      <td>
                        <a href="{% url 'inventory:asset_update' delivery.asset_id %}">
                          {{ delivery.paid }}
                        </a>
                      </td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>

                {% if is_paginated %}
                  <nav aria-label="Page navigation example" class='mt-4'>
                    <ul class="pagination">
                      {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                        </li>
                      {% else %}

                        <li class="page-item disabled"><span class='page-link '>Previous</span></li>
                      {% endif %}
                      <li class="disabled"><span
                          class='page-link'> Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} </span>
                      </li>
                      {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link"
                                                 href="?page={{ page_obj.next_page_number }}">Next</a></li>
                      {% else %}
                        <li class="page-item disabled"><span class='page-link '>Next</span></li>
                      {% endif %}
                    </ul>
                  </nav>
                {% endif %}

              </div>
              <h4 class="card-title">
                <br>
                <a href="{% url 'inventory:out_all_csv' %}"
                   class="btn btn-lg btn-primary float-left">
                  <i class="fa fa-print"></i>&emsp;Xuất CSV
                </a>
              </h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% block noty %}
    <script>
        {% if messages %}
            {% for message in messages  %}
                toastr.success('{{message}}')
            {% endfor %}
        {% endif %}
    </script>
  {% endblock noty %}
{% endblock content %}
</div>

inventory/templates/inventory/out/single.html
{% extends 'manager/layout.html' %}
{% load static %}
{% block title %} Pay's Info | SkyLove CMS {% endblock title %}
{% block content %}

  <script type="text/javascript">
    function view_image(str) {
      let pic, picsrc;
      pic = document.getElementById("image_view");
      pic.src = str;
      picsrc = document.getElementById("image_source_view");
      picsrc.href = str;
    }
  </script>

  <div class="main-panel">
  <div class="content-wrapper">
    <div class="row">
      <div class="col-lg-12 grid-margin">
        <div class="card">
          <div class="card-body">
            <h4 class="text-center text-primary">
              <i class="fa fa-address-book-o"></i>
              &emsp;THẺ LIỆU TRÌNH [Số: {{ treatment.id }}]
            </h4>
            <hr>
            <div class="row">
              <div class="col-lg-2 col-md-2 d-flex align-items-stretch grid-margin">
                <div class="card border-top border-bottom border-success">
                  <div class="card-body">
                    {% if treatment.customer.thumb.url != null %}
                      <img src="{{ treatment.customer.thumb.url }}" alt="" class="img-fluid" width='200px'
                           height='200px'>
                    {% else %}
                      <img src="{% static 'images/No_Image.png' %}" alt="" class="img-fluid" width='200px'
                           height='200px'>
                    {% endif %}
                    <p class="lead mt-2 text-center">
                      {{ treatment.customer.humanID | capfirst }} <br>
                      <small class='text-center text-secondary'>( Photo-ID )</small>
                    </p>

                  </div>
                </div>


              </div>
              <!-- Second column -->
              <div class="col-lg-6 col-md-6">
                <div class="table-responsive border-top border-success table-striped">
                  <p class="lead text-center mt-2">Thông tin KH</p>
                  <table class="table">
                    <tr>
                      <th style="width:50%">Họ tên K/H:</th>
                      <td>{{ treatment.customer.fullname }}</td>
                    </tr>
                    <tr>
                      <th>Điện thoại:</th>
                      <td>{{ treatment.customer.mobile }}</td>
                    </tr>
                    <tr>
                      <th>Dịch vụ</th>
                      <td>{{ treatment.service.name }}</td>
                    </tr>
                    <tr>
                      <th>Ngày mua</th>
                      <td>{{ treatment.dateapply }}</td>
                    </tr>
                    <tr>
                      <th>Ngày hết hạn</th>
                      <td>{{ treatment.dateend }}</td>
                    </tr>
                    <tr>
                      <th>Tư vấn viên</th>
                      <td>{{ treatment.consultant.fullname }}</td>
                    </tr>
                    <tr>
                      <th>Chuyên viên</th>
                      <td>{{ treatment.expert.fullname }}</td>
                    </tr>
                    <tr>
                      <th>Bác sĩ</th>
                      <td>{{ treatment.doctor.fullname }}</td>
                    </tr>
                    <tr>
                      <th>Ghi chú</th>
                      <td>{{ treatment.note }}</td>
                    </tr>
                  </table>

                </div>
                <div class="text-center mt-3">
                  <a href=" {% url 'action:treatment_update' pk=treatment.pk %}"
                     class="btn btn-lg btn-primary">
                    <i class="fa fa-download"></i>&emsp;Cập nhật
                  </a>
                  <a class=""></a>
                  <!---<a href="% url 'action:treatment_overview' %}"--->
                  <a href="javascript:history.back()"
                     class="btn btn-lg btn-primary">
                    <i class="mdi mdi-exit-to-app"></i>Trở lại
                  </a>
                </div>
              </div>
              <!-- Third column-->
              <div class="col-lg-4 col-md-4">
                <div class="table-responsive border-top border-success  table-striped">
                  <p class="lead text-center mt-2">Quá trình trị liệu</p>
                  <table class="table">
                    {% for treat_pro in treat_pros %}
                      <tr>
                        <th>{{ treat_pro.date }}</th>
                        <td>
                          <a href="{% url 'action:treatment_pro_update' pk=treat_pro.id %}">{{ treat_pro.status }}</a>
                        </td>
                        <td>
                          {% for treat_pro_image in treat_pro_images %}
                            {% if treat_pro_image.treat_pro == treat_pro.id %}
                              {% if treat_pro_image.thumb.url != null %}
                                <img src="{{ treat_pro_image.thumb.url }}"
                                     alt="" class="img-fluid" width='20px' height='20px'
                                     onclick="view_image('{{ treat_pro_image.thumb.url }}')"
                                >
                              {% endif %}
                            {% endif %}
                          {% endfor %}
                        </td>
                      </tr>
                    {% endfor %}
                  </table>
                </div>
                <div class="row">
                  <div class="table">
                    {% if treat_pro_images %}
                      <a id="image_source_view" href="{{ treat_pro_images.first.thumb.url }}">
                        <img id="image_view" src="{{ treat_pro_images.first.thumb.url }}"
                             alt="" class="img-fluid" width='250px' height='250px'>
                      </a>
                    {% endif %}
                  </div>
                </div>
                <div class="text-center mt-3">
                  <a href=" {% url 'action:treatment_append' pk=treatment.pk %}"
                     class="btn btn-primary">
                    <i class="fa fa-plus"></i>&emsp;Thêm liệu trình
                  </a>
                </div>

              </div>
            </div>

          </div>

        </div>
      </div>
    </div>
  </div>

{% endblock content %}
</div>