SkyLove/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from SkyLove import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('manager.urls', namespace='manager')),
    path('', include('apptevent.urls', namespace='apptevent')),
    path('', include('inventory.urls', namespace='inventory')),
    path('', include('action.urls', namespace='action')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)
urlpatterns += static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)

action/urls.py
from django.urls import path
from . import views

app_name = 'action'

urlpatterns = [

  # Treatment Routes
  path('treatment/overview', views.treatment_overview, name='treatment_overview'),
  path('treatment/new/', views.TreatmentNew.as_view(), name='treatment_new'),
  path('treatment/newaddfee/', views.treatment_new, name='treatment_new_add_fee'),
  path('treatment/<int:pk>/view/', views.TreatmentView.as_view(), name='treatment_view'),
  path('treatment/<int:pk>/update/', views.TreatmentUpdate.as_view(), name='treatment_update'),
  path('treatment/<int:pk>/append/', views.TreatmentAppend.as_view(), name='treatment_append'),
  # path('treatment/<int:pk>/delete/', views.TreatmentTag_Delete.as_view(), name='treatment_delete'),

  path('treatmentpro/<int:pk>/update/', views.TreatmentProcessUpdate.as_view(), name='treatment_pro_update'),
  path('treatmentpro/<int:pk>/addimg/', views.upload_images, name='treatment_pro_add_img'),
  path('treatmentpro/<int:pk>/preimg/', views.image_preview, name='treatment_pro_prev_img'),
  path('treatmentpro/<int:pk>/deltmpimgs/', views.delete_tmp_images, name='treatment_pro_del_tmp_img'),
  path('treat_img_delete/<int:pk>/<int:img_tag>',
       views.treatment_process_update_delete,
       name='treatment_pro_update_delete'),

  path('treatment/<int:pk>/asset/', views.TreatmentAssetAdd.as_view(), name='treatment_asset'),
  path('treatment/<int:pk>/assetedit/', views.TreatmentAssetUpdate.as_view(), name='treatment_asset_edit'),

  # Consulting Routes
  path('consultant/overview', views.consulting_overview, name='consultant_overview'),
  path('consultant/new/', views.ConsultingNew.as_view(), name='consultant_new'),
  path('consultant/<int:pk>/view/', views.ConsultingView.as_view(), name='consultant_view'),
  path('consultant/<int:pk>/update/', views.ConsultingUpdate.as_view(), name='consultant_update'),

  # Invoice
  path('invoice/overview', views.invoice_overview, name='invoice_overview'),
  path('invoice/new/', views.InvoiceNew.as_view(), name='invoice_new'),
  path('invoice/<int:pk>/view/', views.InvoiceView.as_view(), name='invoice_view'),
  path('invoice/<int:pk>/viewpdf/', views.InvoiceViewPdf.as_view(), name='invoice_view_pdf'),
  path('invoice/<int:pk>/update/', views.InvoiceUpdate.as_view(), name='invoice_update'),
  path('invoice/<int:pk>/append/', views.InvoiceAppend.as_view(), name='invoice_append'),

  path('invoice/debt', views.invoice_debt, name='invoice_debt'),
  path('invoice/debt/csv', views.debt_view_csv, name='invoice_debt_csv'),

  path('invoicepro/<int:pk>/update/', views.InvoiceProcessUpdate.as_view(), name='invoice_pro_update'),
  path('invoicefee/<int:pk>/init/', views.InvoiceFeeInit.as_view(), name='invoice_fee_init'),
  path('invoicefee/<int:pk>/copy/', views.InvoiceFeeCopy.as_view(), name='invoice_fee_copy'),
  path('invoicefee/<int:pk>/update/', views.InvoiceFeeUpdate.as_view(), name='invoice_fee_update'),
  path('invoicefee/<int:pk>/append/', views.InvoiceAppendFee.as_view(), name='invoice_fee_append'),

  path('invoice/<int:pk>/prt', views.invoice_exp_pdf, name='invoice_prt_demo'),

]

inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [

    # Asset Routes
    path('asset/', views.AssetAll.as_view(), name='asset_all'),
    path('asset/new/', views.AssetNew.as_view(), name='asset_new'),
    path('asset/<int:pk>/update/', views.AssetUpdate.as_view(), name='asset_update'),
    path('asset/<int:pk>/view/', views.AssetView.as_view(), name='asset_view'),

    # Inventory Routes
    path('inventory/', views.inventory_overview, name='inv_all'),
    path('inventory/csv/', views.inventory_view_csv, name='inv_all_csv'),
    path('inventory/new/', views.PurchaseNew.as_view(), name='inv_new'),

    path('invout/overview/', views.deliver_overview, name='out_all'),
    path('invout/csv/', views.delivery_view_csv, name='out_all_csv'),

    # AssetCategory Routes
    path('assetcategory/', views.AssetCategoryAll.as_view(), name='ass_cat_all'),
    path('assetcategory/new/', views.AssetCategoryNew.as_view(), name='ass_cat_new'),
    path('assetcategory/<int:pk>/update/', views.AssetCategoryUpdate.as_view(), name='ass_cat_update'),

    # AssetUnit Routes
    path('assetunit/', views.AssetUnitAll.as_view(), name='ass_unt_all'),
    path('assetunit/new/', views.AssetUnitNew.as_view(), name='ass_unt_new'),
    path('assetunit/<int:pk>/update/', views.AssetUnitUpdate.as_view(), name='ass_unt_update'),

    # Supplier Routes
    path('supplier/', views.SupplierAll.as_view(), name='supplier_all'),
    path('supplier/new/', views.SupplierNew.as_view(), name='supplier_new'),
    path('supplier/<int:pk>/update/', views.SupplierUpdate.as_view(), name='supplier_update'),
    path('supplier/<int:pk>/view/', views.SupplierView.as_view(), name='supplier_view'),

]

manager/urls.py
from django.urls import path
from . import views

app_name = 'manager'

urlpatterns = [
    # Authentication Routes
    path('', views.Index.as_view(), name='index'),
    path('register/', views.Register.as_view(), name='reg'),
    path('login/', views.LoginViewer.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('user/<int:pk>/update', views.UserUpdate.as_view(), name='user_update'),
    path('user/password_change', views.password_change, name='user_password_change'),

    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path('birthday/', views.BirthdayView.as_view(), name='birthday'),

    # Employee Routes
    path('employee/', views.EmployeeAll.as_view(), name='employee_all'),
    path('employee/new/', views.EmployeeNew.as_view(), name='employee_new'),
    path('employee/<int:pk>/view/', views.EmployeeView.as_view(), name='employee_view'),
    path('employee/<int:pk>/update/', views.EmployeeUpdate.as_view(), name='employee_update'),
    path('employee/<int:pk>/delete/', views.EmployeeDelete.as_view(), name='employee_delete'),

    # Department Routes
    path('department/all/', views.DepartmentAll.as_view(), name='dept_all'),
    path('department/add/', views.DepartmentNew.as_view(), name='dept_new'),
    path('department/<int:pk>/update/', views.DepartmentUpdate.as_view(), name='dept_update'),

    # path('customer/dashboard', views.Dashboard.as_view(), name='dashboard'),
    path('customer/overview', views.customer_overview, name='customer_overview'),
    path('customer/all', views.CustomerAll.as_view(), name='customer_all'),
    path('customer/new/', views.CustomerNew.as_view(), name='customer_new'),
    path('customer/<int:pk>/view/', views.CustomerView.as_view(), name='customer_view'),
    path('customer/<int:pk>/update/', views.CustomerUpdate.as_view(), name='customer_update'),
    path('customer/<int:pk>/delete/', views.CustomerDelete.as_view(), name='customer_delete'),

    # Customer Source Routes
    path('customer/source/', views.CustomerSourceAll.as_view(), name='cust_src_all'),
    path('customer/source/add/', views.CustomerSourceNew.as_view(), name='cust_src_new'),
    path('customer/source/<int:pk>/update/', views.CustomerSourceUpdate.as_view(), name='cust_src_update'),

    # Service Routes
    path('service/', views.ServiceAll.as_view(), name='app_srv_all'),
    path('service/add/', views.ServiceNew.as_view(), name='app_srv_new'),
    path('service/<int:pk>/update/', views.ServiceUpdate.as_view(), name='app_srv_update'),

]

action/forms.py
from django import forms

from action.models import Treatment, TreatmentProcess, Consulting, Invoice, InvoiceProcess, TreatmentAsset, InvoiceFee
from inventory.models import Asset
from manager.models import Employee, Customer, Service


class ConsultingForm(forms.ModelForm):
    customer = \
        forms.ModelChoiceField(
            Customer.objects.all(),
            label='Khách Hàng:',
            widget=forms.Select(attrs={'class': 'form-control'})
        )
    consultor = \
        forms.ModelChoiceField(
            Employee.objects.all(),
            label='Tư vấn :',
            widget=forms.Select(attrs={'class': 'form-control'})
        )
    date = \
        forms.DateField(
            label='Ngày:',
            widget=forms.DateInput(
                attrs={'type': 'date', 'format': '%d %m %Y'},
                format='%Y-%m-%d',
            )
            # widget=DatePickerInput()
        )
    request = \
        forms.CharField(
            label='Yêu cầu của K/H:',
            required=False,
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Request'})
        )
    medicalhistory = \
        forms.CharField(
            label='Tiền sử bệnh lý:',
            required=False,
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Medical history'})
        )
    health = \
        forms.CharField(
            label='Sức khỏe hiện tại:',
            required=False,
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Health'})
        )

    class Meta:
        model = Consulting
        fields = '__all__'


class ConsultingFilterForm(forms.Form):
    mobile: forms.CharField()


class TreatmentForm(forms.ModelForm):
    service = \
        forms.ModelChoiceField(
            Service.objects.all(),
            label='Dịch vụ:',
            widget=forms.Select(attrs={'class': 'form-control'})
        )
    customer = \
        forms.ModelChoiceField(
            Customer.objects.all(),
            label='Khách Hàng:',
            widget=forms.Select(attrs={'class': 'form-control'})
        )
    date_apply = \
        forms.DateField(
            label='Ngày mua:',
            widget=forms.DateInput(attrs={'type': 'date'}, format='%Y-%m-%d')
            # widget=DatePickerInput()
        )
    date_end = \
        forms.DateField(
            required=False,
            label='Ngày hết hạn:',
            widget=forms.DateInput(attrs={'type': 'date'}, format='%Y-%m-%d')
            # widget=DatePickerInput()
        )
    consultant = \
        forms.ModelChoiceField(
            Employee.objects.all(),
            label='Tư vấn viên:',
            required=False,
            widget=forms.Select(attrs={'class': 'form-control'})
        )
    expert = \
        forms.ModelChoiceField(
            Employee.objects.filter(department=3),
            label='Chuyên viên:',
            required=False,
            widget=forms.Select(attrs={'class': 'form-control'})
        )
    doctor = \
        forms.ModelChoiceField(
            Employee.objects.filter(department=3),
            label='Bác sĩ:',
            required=False,
            widget=forms.Select(attrs={'class': 'form-control'})
        )
    note = \
        forms.CharField(
            label='Ghi chú:',
            required=False,
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Description'})
        )

    class Meta:
        model = Treatment
        fields = ('service', 'customer', 'consultant', 'expert', 'doctor', 'date_apply', 'date_end', 'note')


class TreatmentFilterForm(forms.Form):
    mobile: forms.CharField()


class TreatmentAppendForm(forms.ModelForm):
    """
    tag = \
      forms.IntegerField(
        label='Yêu cầu nhập đúng con số ở trên:',
        widget=forms.NumberInput()
      )
    """
    date = \
        forms.DateField(
            label='Ngày cập nhật:',
            widget=forms.DateInput(attrs={'type': 'date'}, format='%Y-%m-%d')
            # widget=DatePickerInput()
        )
    status = \
        forms.CharField(
            label='Tình trạng:',
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Warranty'})
        )
    thumb = \
        forms.ImageField(
            required=False,
            label='Hình ảnh:',
            widget=forms.ClearableFileInput(attrs={'class': 'form-control'})
        )

    class Meta:
        model = TreatmentProcess
        fields = ('date', 'status', 'thumb')


class TreatmentProcessForm(forms.ModelForm):
    date = \
        forms.DateField(
            label='Ngày:',
            widget=forms.DateInput(attrs={'type': 'date'}, format='%Y-%m-%d')
            # widget=DatePickerInput()
        )
    status = \
        forms.CharField(
            label='Tình trạng:',
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Warranty'})
        )
    # tmp_thumb = \
    #     forms.ImageField(
    #         required=False,
    #         label='Thêm ảnh:',
    #         widget=forms.ClearableFileInput(attrs={'class': 'form-control'})
    #     )

    class Meta:
        model = TreatmentProcess
        fields = ('date', 'status')


class TreatmentAssetForm(forms.ModelForm):
    asset = forms.ModelChoiceField(
        # Asset.objects.all(),
        Asset.objects.filter(inventory__quantityIO__gt=0).order_by('name').distinct(),
        label='Y dụng cụ:',
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    quantity = forms.IntegerField(
        label='Số lượng:',
        widget=forms.NumberInput()
    )

    class Meta:
        model = TreatmentAsset
        fields = ('asset', 'quantity')


class InvoiceForm(forms.ModelForm):
    time = \
        forms.DateTimeField(
            label='Thời gian:',
            widget=forms.DateInput(attrs={'type': 'date'}, format='%Y-%m-%d')
            # widget=DatePickerInput()
        )
    customer = \
        forms.ModelChoiceField(
            Customer.objects.filter(
                deleted=False).exclude(id__in=Invoice.objects.values('customer_id')).order_by('fullname'),
            label='Khách Hàng:',
            widget=forms.Select(attrs={'class': 'form-control'})
        )

    class Meta:
        model = Invoice
        fields = ('time', 'customer',)


class InvoiceFilterForm(forms.Form):
    mobile: forms.CharField()


class InvoiceProcessForm(forms.ModelForm):
    time = \
        forms.DateTimeField(
            label='Thời gian:',
            widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%d %H:%M')
            # widget=DatePickerInput()
        )
    description = \
        forms.CharField(
            label='Diễn giải:',
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Warranty'})
        )
    payby = \
        forms.ChoiceField(
            label='Hình thức:',
            choices=InvoiceProcess.PAYKIND, widget=forms.Select(attrs={'class': 'form-control'})
        )

    class Meta:
        model = InvoiceProcess
        fields = ('time', 'description', 'paid', 'payby')
        labels = {'paid': 'Số tiền:'}


class InvoiceAppendForm(forms.ModelForm):
    """
    time = \
        forms.DateTimeField(
            label='Thời gian:',
            widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%d %H:%M')
            # widget=DatePickerInput()
        )
    """
    description = \
        forms.CharField(
            label='Diễn giải:',
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Description'})
        )
    payby = \
        forms.ChoiceField(
            label='Hình thức:',
            choices=InvoiceProcess.PAYKIND, widget=forms.Select(attrs={'class': 'form-control'})
        )

    class Meta:
        model = InvoiceProcess
        fields = ('description', 'paid', 'payby')
        labels = {'paid': 'Số tiền:'}


class InvoiceFeeForm(forms.ModelForm):
    service = forms.CharField(
        label='Dịch vụ',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Service'})
    )

    class Meta:
        model = InvoiceFee
        fields = ('service', 'price')
        labels = {'price': 'Giá:'}


class InvoiceFeeCopyForm(forms.ModelForm):
    class Meta:
        model = InvoiceFee
        fields = ()


class InvoiceAppendFeeForm(forms.ModelForm):
    """
    time = \
        forms.DateTimeField(
            label='Thời gian:',
            widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%d %H:%M')
            # widget=DatePickerInput()
        )
    """
    service = \
        forms.CharField(
            label='Dịch vụ:',
            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Service'})
        )

    class Meta:
        model = InvoiceFee
        fields = ('service', 'price')
        labels = {'price': 'Số tiền:'}

action/templates/action/treatment/overview.html
{% extends 'manager/layout.html' %}
{% load static %}
{% block title %} All Treatment's Customers | SkyLove CMS {% endblock title %}
<!--  MAIN BODY START HERE -->
{% block content %}
  <div class="main-panel">
  <div class="content-wrapper">
    <div class="row">
      <div class="row">
        <div class="col-lg-12 grid-margin">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title text-primary">
                Liệu trình [
                  {% if treat_total and treat_lookup %}{{ treat_lookup }} / {{ treat_total }}{% endif %} ]
                <form method="GET" action="{% url 'action:treatment_overview' %}">
                  {{ form.as_p }}
                  <label for="mobile">Số điện thoại:</label>
                  <input type="text" id="mobile" name="mobile" value="" maxlength="12"
                         style="color: yellow; background: #015581">
                  <label for="fname">& Tên:</label>
                  <input type="text" id="fname" name="fname" value="" maxlength="20"
                         style="color: yellow; background: #015581">
                  <input type="submit" VALUE="Tìm" class="btn btn-primary"/>

                </form>
                <h4 class="card-title">
                <a href="{% url 'action:treatment_new' %}"
                   class="btn btn-lg btn-primary mb-3 float-left">
                  <i class="fa fa-plus"></i>&emsp;Tạo Thẻ liệu trình
                </a>
                </h4>
                <br>
              </h4>
              <!---  Table contain customer list --->
              <div class="table-responsive">
                <table class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>
                      Photo
                    </th>
                    <th>
                      Họ tên
                    </th>
                    <th>
                      Số điện thoại
                    </th>
                    <th>
                      Dịch vụ
                    </th>
                    <th>
                      Ngày mua
                    </th>
                  </tr>
                  </thead>
                  <tbody>
                  {% for treatment in treatments %}
                    <tr>
                      <td class="font-weight-medium">
                        <a href="{% url 'action:treatment_view' pk=treatment.pk %}">
                          {% if treatment.customer.thumb.url != null %}
                            <img src="{{ treatment.customer.thumb.url }}" class='rounded img-fluid' alt="">
                          {% else %}
                            <img src="{% static 'images/No_Image.png' %}" class='rounded img-fluid' alt="">
                          {% endif %}
                        </a>
                      </td>
                      <td>
                        <a href="{% url 'manager:customer_view' pk=treatment.customer.id %}">
                          {{ treatment.customer.fullname }}
                        </a>
                      </td>
                      <td>
                        {{ treatment.customer.mobile }}
                      </td>
                      <td>
                          <a href="{% url 'action:treatment_view' pk=treatment.pk %}">
                            {{ treatment.service.name }}
                          </a>
                      </td>
                      <td>
                        {{ treatment.date_apply }}
                      </td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>

                {% if is_paginated %}
                  <nav aria-label="Page navigation example" class='mt-4'>
                    <ul class="pagination">
                      {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                        </li>
                      {% else %}

                        <li class="page-item disabled"><span class='page-link '>Previous</span></li>
                      {% endif %}
                      <li class="disabled"><span
                          class='page-link'> Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} </span>
                      </li>
                      {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link"
                                                 href="?page={{ page_obj.next_page_number }}">Next</a></li>
                      {% else %}
                        <li class="page-item disabled"><span class='page-link '>Next</span></li>
                      {% endif %}
                    </ul>
                  </nav>
                {% endif %}

              </div>
              <h4 class="card-title">
                <br>
                <a href="{% url 'action:treatment_new' %}"
                   class="btn btn-lg btn-primary mb-3 float-right">
                  <i class="fa fa-plus"></i>&emsp;Tạo Thẻ liệu trình
                </a>
              </h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% block noty %}
    <script>
      {% if messages %}
        {% for message in messages  %}
          toastr.success('{{message}}')
        {% endfor %}
      {% endif %}
    </script>
  {% endblock noty %}
{% endblock content %}
</div>

action/templates/action/treatment/single.html
{% extends 'manager/layout.html' %}
{% load static %}
{% block title %} Treatment's Info | SkyLove CMS {% endblock title %}
{% block content %}

  <script type="text/javascript">
      function view_image(str) {
          let pic, picsrc;
          pic = document.getElementById("image_view");
          pic.src = str;
          picsrc = document.getElementById("image_source_view");
          picsrc.href = str;
      }
  </script>

  <div class="main-panel">
  <div class="content-wrapper">
    <div class="row">
      <div class="col-lg-12 grid-margin">
        <div class="card">
          <div class="card-body">
            <h4 class="text-center text-primary">
              <i class="fa fa-address-book-o"></i>
              &emsp;THẺ LIỆU TRÌNH [Số: {{ treatment.id }}]
            </h4>
            <hr>
            <div class="row">
              <div class="col-lg-2 col-md-2 d-flex align-items-stretch grid-margin">
                <div class="card border-top border-bottom border-success">
                  <div class="card-body">
                    {% if treatment.customer.thumb.url != null %}
                      <img src="{{ treatment.customer.thumb.url }}" alt="" class="img-fluid" width='200px'
                           height='200px'>
                    {% else %}
                      <img src="{% static 'images/No_Image.png' %}" alt="" class="img-fluid" width='200px'
                           height='200px'>
                    {% endif %}
                    <p class="lead mt-2 text-center">
                      {{ treatment.customer.humanID | capfirst }} <br>
                      <small class='text-center text-secondary'>( Photo-ID )</small>
                    </p>

                  </div>
                </div>


              </div>
              <!-- Second column -->
              <div class="col-lg-6 col-md-6">
                <div class="table-responsive border-top border-success table-striped">
                  <p class="lead text-center mt-2">Thông tin chung</p>
                  <table class="table">
                    <tr>
                      <th style="width:50%">Họ tên K/H:</th>
                      <td>{{ treatment.customer.fullname }}</td>
                    </tr>
                    <tr>
                      <th>Điện thoại:</th>
                      <td>{{ treatment.customer.mobile }}</td>
                    </tr>
                    <tr>
                      <th>Dịch vụ</th>
                      <td>{{ treatment.service.name }}</td>
                    </tr>
                    <tr>
                      <th>Ngày mua</th>
                      <td>{{ treatment.date_apply }}</td>
                    </tr>
                    <tr>
                      <th>Ngày hết hạn</th>
                      <td>{{ treatment.date_end }}</td>
                    </tr>
                    <tr>
                      <th>Tư vấn viên</th>
                      <td>{{ treatment.consultant.fullname }}</td>
                    </tr>
                    <tr>
                      <th>Chuyên viên</th>
                      <td>{{ treatment.expert.fullname }}</td>
                    </tr>
                    <tr>
                      <th>Bác sĩ</th>
                      <td>{{ treatment.doctor.fullname }}</td>
                    </tr>
                    <tr>
                      <th>Ghi chú</th>
                      <td>{{ treatment.note }}</td>
                    </tr>
                  </table>

                </div>
                <div class="text-center mt-3">
                  <a href=" {% url 'action:treatment_update' pk=treatment.pk %}"
                     class="btn btn-lg btn-primary">
                    <i class="fa fa-download"></i>&emsp;Sửa đổi
                  </a>
                  <a class=""></a>
                  <!---<a href="% url 'action:treatment_overview' %}"--->
                  <a href="javascript:history.back()"
                     class="btn btn-lg btn-primary">
                    <i class="mdi mdi-exit-to-app"></i>Trở lại
                  </a>
                </div>
              </div>
              <!-- Third column-->
              <div class="col-lg-4 col-md-4">
                <div class="table-responsive border-top border-success  table-striped">
                  <p class="lead text-center mt-2">Quá trình trị liệu</p>
                  <table class="table">
                    {% for treat_pro in treat_pros %}
                      <tr>
                        <th>{{ treat_pro.date }}</th>
                        <td>
                          <a href="{% url 'action:treatment_pro_update' pk=treat_pro.id %}">{{ treat_pro.status }}</a>
                        </td>
                        <td>
                          {% for treat_pro_image in treat_pro_images %}
                            {% if treat_pro_image.treat_pro == treat_pro.id %}
                              {% if treat_pro_image.thumb.url != null %}
                                <img src="{{ treat_pro_image.thumb.url }}"
                                     alt="" class="img-fluid" width='20px' height='20px'
                                     onclick="view_image('{{ treat_pro_image.thumb.url }}')"
                                >
                              {% endif %}
                            {% endif %}
                          {% endfor %}
                        </td>
                      </tr>
                    {% endfor %}
                  </table>
                </div>
                <div class="row">
                  <div class="table">
                    <!----
                    % if treat_pro_images %}
                        <a id="image_source_view" href="{ treat_pro_images.last.thumb.url }}">
                            <img id="image_view" src="{ treat_pro_images.last.thumb.url }}"
                             alt="" class="img-fluid" width='250px' height='250px'>
                        </a>
                    { endif %}
                    ----->
                  </div>
                </div>
                <div class="text-right mt-3">
                  <a href=" {% url 'action:treatment_append' pk=treatment.pk %}"
                     class="btn btn-primary">
                    <i class="fa fa-plus"></i>&emsp;Thêm liệu trình
                  </a>
                </div>
                <div class="table-responsive border-top border-success  table-striped">
                  <p class="lead text-center mt-2">Vật tư</p>
                  <table class="table">
                    {% for treat_ass in treat_assets %}
                      <tr>
                        <th>
                          <a href=" {% url 'action:treatment_asset_edit' pk=treat_ass.id %}">
                            {{ treat_ass.asset_name }}
                          </a>
                        </th>
                        <td>
                          <a href=" {% url 'action:treatment_asset_edit' pk=treat_ass.id %}">
                            {{ treat_ass.asset_quantity }}
                          </a>
                        </td>
                        <td>
                          <div class="text-lg-right">
                            <a href=" {% url 'inventory:asset_update' pk=treat_ass.asset_id %}">
                              {{ treat_ass.asset_sum }}
                            </a>
                          </div>
                        </td>
                      </tr>
                    {% endfor %}
                    <tr>
                      <th>
                        <div class="text-lg-right">
                          Tổng cộng:
                        </div>
                      </th>
                      <td>
                      </td>
                      <td>
                        <div class="text-danger text-lg-right">
                          {{ sum_price }}
                        </div>
                      </td>
                    </tr>
                  </table>
                </div>
                <div class="text-right mt-3">
                  <a href=" {% url 'action:treatment_asset' pk=treatment.pk %}"
                     class="btn btn-primary">
                    <i class="fa fa-plus"></i>&emsp;Thêm Vật tư
                  </a>
                </div>
                <div class="text-lg-left mt-3">
                  {% if invoice_id is not None %}
                    <a href=" {% url 'action:invoice_view' pk=invoice_id %}"
                       class="btn btn-primary">
                      <i class="fa fa-money"></i>&emsp;Thanh toán
                    </a>
                  {% else %}
                    <a href=" {% url 'action:invoice_new' %}"
                       class="btn btn-primary">
                      <i class="mdi mdi-file-account"></i>&emsp;Mở sổ
                    </a>
                  {% endif %}
                </div>
              </div>
            </div>

          </div>

        </div>
      </div>
    </div>
  </div>

{% endblock content %}
</div>